name: ActiveList
description: A plugin to see active players and last login dates
author: Hykilpikonna

main: org.hydev.mc.ActiveList
version: 1.0
api-version: 1.14

commands:
  activelist:
    description: View the active list of players' last login dates
    usage: /activelist [page=1] [pageSize=10] [-a/-d (sort ascending or descending)]
    permission: activelist.view
