name: ActiveList
description: A plugin to see active players and last login dates
author: Hykilpikonna

main: org.hydev.mc.ActiveList
version: 1.1
api-version: 1.17

load: POSTWORLD
depend: [Essentials]

commands:
  activelist:
    description: View the active list of players' last login dates
    aliases:
      - al
      - ll
    usage: /activelist [page=1] [pageSize=10] [-a/-d (sort ascending or descending)]
    permission: activelist.view
